channels:
- conda-forge
dependencies:
- python=3.11.3
- pip<=24.3.1
- pip:
  - mlflow==2.19.0
  - cloudpickle==3.1.0
  - numpy==1.24.3
  - psutil==5.9.5
  - scikit-learn==1.3.2
  - scipy==1.10.1
name: mlflow-env
